### ISSUE TITLE
train.tf_record not found error

### ISSUE THREAD

**Issue by chandreshiit** [javaidnabi31/Multi-Label-Text-classification-Using-BERT#6]
Hi, Can you tell me where did you get that file i.e. "train.tf_record"?

**Comment by bakarin** [comment]
That file is automatically being created. I think, you need to manually create a "working" folder in your directory prior to running the code. The train.tf_record will be placed in there together with the model output.

**Comment by chandreshiit** [comment]
ok. Thanks.
